with-expecter: true
outpkg: mocks
dir: mocks
packages:
  github.com/MargonDiego/GOAPI/internal/domain:
    interfaces:
      UserRepository:
      RoleRepository:
      AuditRepository:
      EstudianteRepository:
      IncidenciaRepository:
      FileStorage:
  github.com/MargonDiego/GOAPI/internal/application:
    interfaces:
      AuthService:
      UserService:
      RoleService:
      EstudianteService:
      IncidenciaService:
