with-expecter: true
outpkg: mocks
dir: mocks
packages:
  github.com/MargonDiego/GOAPI/internal/domain:
    interfaces:
      UserRepository:
      RoleRepository:
      EstudianteRepository:
  github.com/MargonDiego/GOAPI/internal/application:
    interfaces:
      AuthService:
      UserService:
      RoleService:
