// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/diego/go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

type MockRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleService) EXPECT() *MockRoleService_Expecter {
	return &MockRoleService_Expecter{mock: &_m.Mock}
}

// AssignPermissionsToRole provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *MockRoleService) AssignPermissionsToRole(ctx context.Context, roleID uint, permissionIDs []uint) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionsToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_AssignPermissionsToRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermissionsToRole'
type MockRoleService_AssignPermissionsToRole_Call struct {
	*mock.Call
}

// AssignPermissionsToRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint
//   - permissionIDs []uint
func (_e *MockRoleService_Expecter) AssignPermissionsToRole(ctx interface{}, roleID interface{}, permissionIDs interface{}) *MockRoleService_AssignPermissionsToRole_Call {
	return &MockRoleService_AssignPermissionsToRole_Call{Call: _e.mock.On("AssignPermissionsToRole", ctx, roleID, permissionIDs)}
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) Run(run func(ctx context.Context, roleID uint, permissionIDs []uint)) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) Return(_a0 error) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function with given fields: ctx, name
func (_m *MockRoleService) CreateRole(ctx context.Context, name string) (*domain.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockRoleService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleService_Expecter) CreateRole(ctx interface{}, name interface{}) *MockRoleService_CreateRole_Call {
	return &MockRoleService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, name)}
}

func (_c *MockRoleService_CreateRole_Call) Run(run func(ctx context.Context, name string)) *MockRoleService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleService_CreateRole_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleService_CreateRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_CreateRole_Call) RunAndReturn(run func(context.Context, string) (*domain.Role, error)) *MockRoleService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx
func (_m *MockRoleService) GetPermissions(ctx context.Context) ([]domain.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockRoleService_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) GetPermissions(ctx interface{}) *MockRoleService_GetPermissions_Call {
	return &MockRoleService_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *MockRoleService_GetPermissions_Call) Run(run func(ctx context.Context)) *MockRoleService_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleService_GetPermissions_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleService_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetPermissions_Call) RunAndReturn(run func(context.Context) ([]domain.Permission, error)) *MockRoleService_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx
func (_m *MockRoleService) GetRoles(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockRoleService_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) GetRoles(ctx interface{}) *MockRoleService_GetRoles_Call {
	return &MockRoleService_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx)}
}

func (_c *MockRoleService_GetRoles_Call) Run(run func(ctx context.Context)) *MockRoleService_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleService_GetRoles_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleService_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetRoles_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleService_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
