// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockAuthService) Login(ctx context.Context, username string, password string) (string, string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(accessToken string, refreshToken string, err error) *MockAuthService_Login_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) Logout(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, userID interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, userID)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, userID uint)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, uint) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) RefreshTokens(ctx context.Context, refreshToken string) (string, string, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuthService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *MockAuthService_RefreshTokens_Call {
	return &MockAuthService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *MockAuthService_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) Return(accessToken string, newRefreshToken string, err error) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(accessToken, newRefreshToken, err)
	return _c
}

func (_c *MockAuthService_RefreshTokens_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *MockAuthService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, username, password, email
func (_m *MockAuthService) Register(ctx context.Context, username string, password string, email string) error {
	ret := _m.Called(ctx, username, password, email)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, username, password, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - email string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, username interface{}, password interface{}, email interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, username, password, email)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, username string, password string, email string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
