// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/diego/go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleService is an autogenerated mock type for the RoleService type
type MockRoleService struct {
	mock.Mock
}

type MockRoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleService) EXPECT() *MockRoleService_Expecter {
	return &MockRoleService_Expecter{mock: &_m.Mock}
}

// AssignPermissionsToRole provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *MockRoleService) AssignPermissionsToRole(ctx context.Context, roleID uint, permissionIDs []uint) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermissionsToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_AssignPermissionsToRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermissionsToRole'
type MockRoleService_AssignPermissionsToRole_Call struct {
	*mock.Call
}

// AssignPermissionsToRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint
//   - permissionIDs []uint
func (_e *MockRoleService_Expecter) AssignPermissionsToRole(ctx interface{}, roleID interface{}, permissionIDs interface{}) *MockRoleService_AssignPermissionsToRole_Call {
	return &MockRoleService_AssignPermissionsToRole_Call{Call: _e.mock.On("AssignPermissionsToRole", ctx, roleID, permissionIDs)}
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) Run(run func(ctx context.Context, roleID uint, permissionIDs []uint)) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]uint))
	})
	return _c
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) Return(_a0 error) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_AssignPermissionsToRole_Call) RunAndReturn(run func(context.Context, uint, []uint) error) *MockRoleService_AssignPermissionsToRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePermission provides a mock function with given fields: ctx, name, description
func (_m *MockRoleService) CreatePermission(ctx context.Context, name string, description string) error {
	ret := _m.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_CreatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermission'
type MockRoleService_CreatePermission_Call struct {
	*mock.Call
}

// CreatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
func (_e *MockRoleService_Expecter) CreatePermission(ctx interface{}, name interface{}, description interface{}) *MockRoleService_CreatePermission_Call {
	return &MockRoleService_CreatePermission_Call{Call: _e.mock.On("CreatePermission", ctx, name, description)}
}

func (_c *MockRoleService_CreatePermission_Call) Run(run func(ctx context.Context, name string, description string)) *MockRoleService_CreatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleService_CreatePermission_Call) Return(_a0 error) *MockRoleService_CreatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_CreatePermission_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleService_CreatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function with given fields: ctx, name, description
func (_m *MockRoleService) CreateRole(ctx context.Context, name string, description string) (*domain.Role, error) {
	ret := _m.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Role, error)); ok {
		return rf(ctx, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Role); ok {
		r0 = rf(ctx, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockRoleService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
func (_e *MockRoleService_Expecter) CreateRole(ctx interface{}, name interface{}, description interface{}) *MockRoleService_CreateRole_Call {
	return &MockRoleService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, name, description)}
}

func (_c *MockRoleService_CreateRole_Call) Run(run func(ctx context.Context, name string, description string)) *MockRoleService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleService_CreateRole_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleService_CreateRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_CreateRole_Call) RunAndReturn(run func(context.Context, string, string) (*domain.Role, error)) *MockRoleService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function with given fields: ctx, roleID
func (_m *MockRoleService) DeleteRole(ctx context.Context, roleID uint) error {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockRoleService_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint
func (_e *MockRoleService_Expecter) DeleteRole(ctx interface{}, roleID interface{}) *MockRoleService_DeleteRole_Call {
	return &MockRoleService_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, roleID)}
}

func (_c *MockRoleService_DeleteRole_Call) Run(run func(ctx context.Context, roleID uint)) *MockRoleService_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleService_DeleteRole_Call) Return(_a0 error) *MockRoleService_DeleteRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_DeleteRole_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoleService_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeletedRoles provides a mock function with given fields: ctx
func (_m *MockRoleService) GetDeletedRoles(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDeletedRoles")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetDeletedRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeletedRoles'
type MockRoleService_GetDeletedRoles_Call struct {
	*mock.Call
}

// GetDeletedRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) GetDeletedRoles(ctx interface{}) *MockRoleService_GetDeletedRoles_Call {
	return &MockRoleService_GetDeletedRoles_Call{Call: _e.mock.On("GetDeletedRoles", ctx)}
}

func (_c *MockRoleService_GetDeletedRoles_Call) Run(run func(ctx context.Context)) *MockRoleService_GetDeletedRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleService_GetDeletedRoles_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleService_GetDeletedRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetDeletedRoles_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleService_GetDeletedRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx
func (_m *MockRoleService) GetPermissions(ctx context.Context) ([]domain.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockRoleService_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) GetPermissions(ctx interface{}) *MockRoleService_GetPermissions_Call {
	return &MockRoleService_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx)}
}

func (_c *MockRoleService_GetPermissions_Call) Run(run func(ctx context.Context)) *MockRoleService_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleService_GetPermissions_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleService_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetPermissions_Call) RunAndReturn(run func(context.Context) ([]domain.Permission, error)) *MockRoleService_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionsPaginated provides a mock function with given fields: ctx, page, size
func (_m *MockRoleService) GetPermissionsPaginated(ctx context.Context, page int, size int) (domain.PaginatedResult[domain.Permission], error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsPaginated")
	}

	var r0 domain.PaginatedResult[domain.Permission]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (domain.PaginatedResult[domain.Permission], error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) domain.PaginatedResult[domain.Permission]); ok {
		r0 = rf(ctx, page, size)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.Permission])
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetPermissionsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsPaginated'
type MockRoleService_GetPermissionsPaginated_Call struct {
	*mock.Call
}

// GetPermissionsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockRoleService_Expecter) GetPermissionsPaginated(ctx interface{}, page interface{}, size interface{}) *MockRoleService_GetPermissionsPaginated_Call {
	return &MockRoleService_GetPermissionsPaginated_Call{Call: _e.mock.On("GetPermissionsPaginated", ctx, page, size)}
}

func (_c *MockRoleService_GetPermissionsPaginated_Call) Run(run func(ctx context.Context, page int, size int)) *MockRoleService_GetPermissionsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoleService_GetPermissionsPaginated_Call) Return(_a0 domain.PaginatedResult[domain.Permission], _a1 error) *MockRoleService_GetPermissionsPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetPermissionsPaginated_Call) RunAndReturn(run func(context.Context, int, int) (domain.PaginatedResult[domain.Permission], error)) *MockRoleService_GetPermissionsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoleByID provides a mock function with given fields: ctx, id
func (_m *MockRoleService) GetRoleByID(ctx context.Context, id uint) (*domain.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByID")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetRoleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleByID'
type MockRoleService_GetRoleByID_Call struct {
	*mock.Call
}

// GetRoleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoleService_Expecter) GetRoleByID(ctx interface{}, id interface{}) *MockRoleService_GetRoleByID_Call {
	return &MockRoleService_GetRoleByID_Call{Call: _e.mock.On("GetRoleByID", ctx, id)}
}

func (_c *MockRoleService_GetRoleByID_Call) Run(run func(ctx context.Context, id uint)) *MockRoleService_GetRoleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleService_GetRoleByID_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleService_GetRoleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetRoleByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Role, error)) *MockRoleService_GetRoleByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx
func (_m *MockRoleService) GetRoles(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockRoleService_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleService_Expecter) GetRoles(ctx interface{}) *MockRoleService_GetRoles_Call {
	return &MockRoleService_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx)}
}

func (_c *MockRoleService_GetRoles_Call) Run(run func(ctx context.Context)) *MockRoleService_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleService_GetRoles_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleService_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetRoles_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleService_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesPaginated provides a mock function with given fields: ctx, page, size
func (_m *MockRoleService) GetRolesPaginated(ctx context.Context, page int, size int) (domain.PaginatedResult[domain.Role], error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesPaginated")
	}

	var r0 domain.PaginatedResult[domain.Role]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (domain.PaginatedResult[domain.Role], error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) domain.PaginatedResult[domain.Role]); ok {
		r0 = rf(ctx, page, size)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.Role])
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_GetRolesPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesPaginated'
type MockRoleService_GetRolesPaginated_Call struct {
	*mock.Call
}

// GetRolesPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockRoleService_Expecter) GetRolesPaginated(ctx interface{}, page interface{}, size interface{}) *MockRoleService_GetRolesPaginated_Call {
	return &MockRoleService_GetRolesPaginated_Call{Call: _e.mock.On("GetRolesPaginated", ctx, page, size)}
}

func (_c *MockRoleService_GetRolesPaginated_Call) Run(run func(ctx context.Context, page int, size int)) *MockRoleService_GetRolesPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoleService_GetRolesPaginated_Call) Return(_a0 domain.PaginatedResult[domain.Role], _a1 error) *MockRoleService_GetRolesPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_GetRolesPaginated_Call) RunAndReturn(run func(context.Context, int, int) (domain.PaginatedResult[domain.Role], error)) *MockRoleService_GetRolesPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreRole provides a mock function with given fields: ctx, roleID
func (_m *MockRoleService) RestoreRole(ctx context.Context, roleID uint) error {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_RestoreRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreRole'
type MockRoleService_RestoreRole_Call struct {
	*mock.Call
}

// RestoreRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint
func (_e *MockRoleService_Expecter) RestoreRole(ctx interface{}, roleID interface{}) *MockRoleService_RestoreRole_Call {
	return &MockRoleService_RestoreRole_Call{Call: _e.mock.On("RestoreRole", ctx, roleID)}
}

func (_c *MockRoleService_RestoreRole_Call) Run(run func(ctx context.Context, roleID uint)) *MockRoleService_RestoreRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleService_RestoreRole_Call) Return(_a0 error) *MockRoleService_RestoreRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_RestoreRole_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoleService_RestoreRole_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRoles provides a mock function with given fields: ctx, query
func (_m *MockRoleService) SearchRoles(ctx context.Context, query string) ([]domain.Role, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchRoles")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleService_SearchRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRoles'
type MockRoleService_SearchRoles_Call struct {
	*mock.Call
}

// SearchRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockRoleService_Expecter) SearchRoles(ctx interface{}, query interface{}) *MockRoleService_SearchRoles_Call {
	return &MockRoleService_SearchRoles_Call{Call: _e.mock.On("SearchRoles", ctx, query)}
}

func (_c *MockRoleService_SearchRoles_Call) Run(run func(ctx context.Context, query string)) *MockRoleService_SearchRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleService_SearchRoles_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleService_SearchRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleService_SearchRoles_Call) RunAndReturn(run func(context.Context, string) ([]domain.Role, error)) *MockRoleService_SearchRoles_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function with given fields: ctx, permID, name, description
func (_m *MockRoleService) UpdatePermission(ctx context.Context, permID uint, name string, description string) error {
	ret := _m.Called(ctx, permID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, permID, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockRoleService_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - permID uint
//   - name string
//   - description string
func (_e *MockRoleService_Expecter) UpdatePermission(ctx interface{}, permID interface{}, name interface{}, description interface{}) *MockRoleService_UpdatePermission_Call {
	return &MockRoleService_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, permID, name, description)}
}

func (_c *MockRoleService_UpdatePermission_Call) Run(run func(ctx context.Context, permID uint, name string, description string)) *MockRoleService_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRoleService_UpdatePermission_Call) Return(_a0 error) *MockRoleService_UpdatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_UpdatePermission_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockRoleService_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, roleID, name, description
func (_m *MockRoleService) UpdateRole(ctx context.Context, roleID uint, name string, description string) error {
	ret := _m.Called(ctx, roleID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, roleID, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRoleService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uint
//   - name string
//   - description string
func (_e *MockRoleService_Expecter) UpdateRole(ctx interface{}, roleID interface{}, name interface{}, description interface{}) *MockRoleService_UpdateRole_Call {
	return &MockRoleService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, roleID, name, description)}
}

func (_c *MockRoleService_UpdateRole_Call) Run(run func(ctx context.Context, roleID uint, name string, description string)) *MockRoleService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRoleService_UpdateRole_Call) Return(_a0 error) *MockRoleService_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleService_UpdateRole_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockRoleService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleService creates a new instance of MockRoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleService {
	mock := &MockRoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
