// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/diego/go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DeleteRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockUserRepository) DeleteRefreshToken(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockUserRepository_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserRepository_Expecter) DeleteRefreshToken(ctx interface{}, token interface{}) *MockUserRepository_DeleteRefreshToken_Call {
	return &MockUserRepository_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, token)}
}

func (_c *MockUserRepository_DeleteRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockUserRepository_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_DeleteRefreshToken_Call) Return(_a0 error) *MockUserRepository_DeleteRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_DeleteRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, page, size
func (_m *MockUserRepository) FindAll(ctx context.Context, page int, size int) ([]domain.User, error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.User, error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.User); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockUserRepository_Expecter) FindAll(ctx interface{}, page interface{}, size interface{}) *MockUserRepository_FindAll_Call {
	return &MockUserRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, page, size)}
}

func (_c *MockUserRepository_FindAll_Call) Run(run func(ctx context.Context, page int, size int)) *MockUserRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserRepository_FindAll_Call) Return(_a0 []domain.User, _a1 error) *MockUserRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]domain.User, error)) *MockUserRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmailHash provides a mock function with given fields: ctx, emailHash
func (_m *MockUserRepository) FindByEmailHash(ctx context.Context, emailHash string) (*domain.User, error) {
	ret := _m.Called(ctx, emailHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmailHash")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, emailHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, emailHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, emailHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByEmailHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmailHash'
type MockUserRepository_FindByEmailHash_Call struct {
	*mock.Call
}

// FindByEmailHash is a helper method to define mock.On call
//   - ctx context.Context
//   - emailHash string
func (_e *MockUserRepository_Expecter) FindByEmailHash(ctx interface{}, emailHash interface{}) *MockUserRepository_FindByEmailHash_Call {
	return &MockUserRepository_FindByEmailHash_Call{Call: _e.mock.On("FindByEmailHash", ctx, emailHash)}
}

func (_c *MockUserRepository_FindByEmailHash_Call) Run(run func(ctx context.Context, emailHash string)) *MockUserRepository_FindByEmailHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByEmailHash_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_FindByEmailHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByEmailHash_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserRepository_FindByEmailHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) FindByID(ctx context.Context, id uint) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserRepository) FindByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockUserRepository_FindByUsername_Call {
	return &MockUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) Return(_a0 *domain.User, _a1 error) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindRoleByName provides a mock function with given fields: ctx, roleName
func (_m *MockUserRepository) FindRoleByName(ctx context.Context, roleName string) (domain.Role, error) {
	ret := _m.Called(ctx, roleName)

	if len(ret) == 0 {
		panic("no return value specified for FindRoleByName")
	}

	var r0 domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Role, error)); ok {
		return rf(ctx, roleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Role); ok {
		r0 = rf(ctx, roleName)
	} else {
		r0 = ret.Get(0).(domain.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindRoleByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRoleByName'
type MockUserRepository_FindRoleByName_Call struct {
	*mock.Call
}

// FindRoleByName is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
func (_e *MockUserRepository_Expecter) FindRoleByName(ctx interface{}, roleName interface{}) *MockUserRepository_FindRoleByName_Call {
	return &MockUserRepository_FindRoleByName_Call{Call: _e.mock.On("FindRoleByName", ctx, roleName)}
}

func (_c *MockUserRepository_FindRoleByName_Call) Run(run func(ctx context.Context, roleName string)) *MockUserRepository_FindRoleByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindRoleByName_Call) Return(_a0 domain.Role, _a1 error) *MockUserRepository_FindRoleByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindRoleByName_Call) RunAndReturn(run func(context.Context, string) (domain.Role, error)) *MockUserRepository_FindRoleByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockUserRepository) GetRefreshToken(ctx context.Context, token string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockUserRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserRepository_Expecter) GetRefreshToken(ctx interface{}, token interface{}) *MockUserRepository_GetRefreshToken_Call {
	return &MockUserRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, token)}
}

func (_c *MockUserRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, token string)) *MockUserRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetRefreshToken_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockUserRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockUserRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) Save(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) Save(ctx interface{}, u interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", ctx, u)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(_a0 error) *MockUserRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: ctx, rt
func (_m *MockUserRepository) SaveRefreshToken(ctx context.Context, rt *domain.RefreshToken) error {
	ret := _m.Called(ctx, rt)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockUserRepository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - rt *domain.RefreshToken
func (_e *MockUserRepository_Expecter) SaveRefreshToken(ctx interface{}, rt interface{}) *MockUserRepository_SaveRefreshToken_Call {
	return &MockUserRepository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, rt)}
}

func (_c *MockUserRepository_SaveRefreshToken_Call) Run(run func(ctx context.Context, rt *domain.RefreshToken)) *MockUserRepository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockUserRepository_SaveRefreshToken_Call) Return(_a0 error) *MockUserRepository_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SaveRefreshToken_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockUserRepository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, u
func (_m *MockUserRepository) Update(ctx context.Context, u *domain.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, u interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, u)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, u *domain.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoles provides a mock function with given fields: ctx, userID, roles
func (_m *MockUserRepository) UpdateRoles(ctx context.Context, userID uint, roles []domain.Role) error {
	ret := _m.Called(ctx, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []domain.Role) error); ok {
		r0 = rf(ctx, userID, roles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoles'
type MockUserRepository_UpdateRoles_Call struct {
	*mock.Call
}

// UpdateRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - roles []domain.Role
func (_e *MockUserRepository_Expecter) UpdateRoles(ctx interface{}, userID interface{}, roles interface{}) *MockUserRepository_UpdateRoles_Call {
	return &MockUserRepository_UpdateRoles_Call{Call: _e.mock.On("UpdateRoles", ctx, userID, roles)}
}

func (_c *MockUserRepository_UpdateRoles_Call) Run(run func(ctx context.Context, userID uint, roles []domain.Role)) *MockUserRepository_UpdateRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].([]domain.Role))
	})
	return _c
}

func (_c *MockUserRepository_UpdateRoles_Call) Return(_a0 error) *MockUserRepository_UpdateRoles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateRoles_Call) RunAndReturn(run func(context.Context, uint, []domain.Role) error) *MockUserRepository_UpdateRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
