// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/diego/go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Create(ctx context.Context, role *domain.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *domain.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, role *domain.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(_a0 error) *MockRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Role) error) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAll(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoleRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAll(ctx interface{}) *MockRoleRepository_FindAll_Call {
	return &MockRoleRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRoleRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissions provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAllPermissions(ctx context.Context) ([]domain.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissions")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissions'
type MockRoleRepository_FindAllPermissions_Call struct {
	*mock.Call
}

// FindAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAllPermissions(ctx interface{}) *MockRoleRepository_FindAllPermissions_Call {
	return &MockRoleRepository_FindAllPermissions_Call{Call: _e.mock.On("FindAllPermissions", ctx)}
}

func (_c *MockRoleRepository_FindAllPermissions_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPermissions_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPermissions_Call) RunAndReturn(run func(context.Context) ([]domain.Permission, error)) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) FindByID(ctx context.Context, id uint) (*domain.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepository_FindByID_Call {
	return &MockRoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockRoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Role, error)) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleRepository) FindPermissionsByIDs(ctx context.Context, ids []uint) ([]domain.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByIDs")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]domain.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []domain.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindPermissionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByIDs'
type MockRoleRepository_FindPermissionsByIDs_Call struct {
	*mock.Call
}

// FindPermissionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockRoleRepository_Expecter) FindPermissionsByIDs(ctx interface{}, ids interface{}) *MockRoleRepository_FindPermissionsByIDs_Call {
	return &MockRoleRepository_FindPermissionsByIDs_Call{Call: _e.mock.On("FindPermissionsByIDs", ctx, ids)}
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]domain.Permission, error)) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindRolesByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleRepository) FindRolesByIDs(ctx context.Context, ids []uint) ([]domain.Role, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindRolesByIDs")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]domain.Role, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []domain.Role); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindRolesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRolesByIDs'
type MockRoleRepository_FindRolesByIDs_Call struct {
	*mock.Call
}

// FindRolesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockRoleRepository_Expecter) FindRolesByIDs(ctx interface{}, ids interface{}) *MockRoleRepository_FindRolesByIDs_Call {
	return &MockRoleRepository_FindRolesByIDs_Call{Call: _e.mock.On("FindRolesByIDs", ctx, ids)}
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]domain.Role, error)) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Update(ctx context.Context, role *domain.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *domain.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, role *domain.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(_a0 error) *MockRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Role) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
