// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/MargonDiego/GOAPI/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// CountPermissions provides a mock function with given fields: ctx
func (_m *MockRoleRepository) CountPermissions(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountPermissions")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_CountPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPermissions'
type MockRoleRepository_CountPermissions_Call struct {
	*mock.Call
}

// CountPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) CountPermissions(ctx interface{}) *MockRoleRepository_CountPermissions_Call {
	return &MockRoleRepository_CountPermissions_Call{Call: _e.mock.On("CountPermissions", ctx)}
}

func (_c *MockRoleRepository_CountPermissions_Call) Run(run func(ctx context.Context)) *MockRoleRepository_CountPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_CountPermissions_Call) Return(_a0 int64, _a1 error) *MockRoleRepository_CountPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_CountPermissions_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockRoleRepository_CountPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// CountRoles provides a mock function with given fields: ctx
func (_m *MockRoleRepository) CountRoles(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountRoles")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_CountRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRoles'
type MockRoleRepository_CountRoles_Call struct {
	*mock.Call
}

// CountRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) CountRoles(ctx interface{}) *MockRoleRepository_CountRoles_Call {
	return &MockRoleRepository_CountRoles_Call{Call: _e.mock.On("CountRoles", ctx)}
}

func (_c *MockRoleRepository_CountRoles_Call) Run(run func(ctx context.Context)) *MockRoleRepository_CountRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_CountRoles_Call) Return(_a0 int64, _a1 error) *MockRoleRepository_CountRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_CountRoles_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockRoleRepository_CountRoles_Call {
	_c.Call.Return(run)
	return _c
}

// CountRolesByScope provides a mock function with given fields: ctx, scope
func (_m *MockRoleRepository) CountRolesByScope(ctx context.Context, scope string) (int64, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for CountRolesByScope")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, scope)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_CountRolesByScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRolesByScope'
type MockRoleRepository_CountRolesByScope_Call struct {
	*mock.Call
}

// CountRolesByScope is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *MockRoleRepository_Expecter) CountRolesByScope(ctx interface{}, scope interface{}) *MockRoleRepository_CountRolesByScope_Call {
	return &MockRoleRepository_CountRolesByScope_Call{Call: _e.mock.On("CountRolesByScope", ctx, scope)}
}

func (_c *MockRoleRepository_CountRolesByScope_Call) Run(run func(ctx context.Context, scope string)) *MockRoleRepository_CountRolesByScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_CountRolesByScope_Call) Return(_a0 int64, _a1 error) *MockRoleRepository_CountRolesByScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_CountRolesByScope_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockRoleRepository_CountRolesByScope_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Create(ctx context.Context, role *domain.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *domain.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, role *domain.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(_a0 error) *MockRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Role) error) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePermission provides a mock function with given fields: ctx, name
func (_m *MockRoleRepository) CreatePermission(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_CreatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermission'
type MockRoleRepository_CreatePermission_Call struct {
	*mock.Call
}

// CreatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) CreatePermission(ctx interface{}, name interface{}) *MockRoleRepository_CreatePermission_Call {
	return &MockRoleRepository_CreatePermission_Call{Call: _e.mock.On("CreatePermission", ctx, name)}
}

func (_c *MockRoleRepository_CreatePermission_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_CreatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_CreatePermission_Call) Return(_a0 error) *MockRoleRepository_CreatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_CreatePermission_Call) RunAndReturn(run func(context.Context, string) error) *MockRoleRepository_CreatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePermissionWithDescription provides a mock function with given fields: ctx, name, description
func (_m *MockRoleRepository) CreatePermissionWithDescription(ctx context.Context, name string, description string) error {
	ret := _m.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermissionWithDescription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_CreatePermissionWithDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermissionWithDescription'
type MockRoleRepository_CreatePermissionWithDescription_Call struct {
	*mock.Call
}

// CreatePermissionWithDescription is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
func (_e *MockRoleRepository_Expecter) CreatePermissionWithDescription(ctx interface{}, name interface{}, description interface{}) *MockRoleRepository_CreatePermissionWithDescription_Call {
	return &MockRoleRepository_CreatePermissionWithDescription_Call{Call: _e.mock.On("CreatePermissionWithDescription", ctx, name, description)}
}

func (_c *MockRoleRepository_CreatePermissionWithDescription_Call) Run(run func(ctx context.Context, name string, description string)) *MockRoleRepository_CreatePermissionWithDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_CreatePermissionWithDescription_Call) Return(_a0 error) *MockRoleRepository_CreatePermissionWithDescription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_CreatePermissionWithDescription_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleRepository_CreatePermissionWithDescription_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(_a0 error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAll(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoleRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAll(ctx interface{}) *MockRoleRepository_FindAll_Call {
	return &MockRoleRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRoleRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByScope provides a mock function with given fields: ctx, scope
func (_m *MockRoleRepository) FindAllByScope(ctx context.Context, scope string) ([]domain.Role, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByScope")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllByScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByScope'
type MockRoleRepository_FindAllByScope_Call struct {
	*mock.Call
}

// FindAllByScope is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *MockRoleRepository_Expecter) FindAllByScope(ctx interface{}, scope interface{}) *MockRoleRepository_FindAllByScope_Call {
	return &MockRoleRepository_FindAllByScope_Call{Call: _e.mock.On("FindAllByScope", ctx, scope)}
}

func (_c *MockRoleRepository_FindAllByScope_Call) Run(run func(ctx context.Context, scope string)) *MockRoleRepository_FindAllByScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllByScope_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAllByScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllByScope_Call) RunAndReturn(run func(context.Context, string) ([]domain.Role, error)) *MockRoleRepository_FindAllByScope_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDeleted provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAllDeleted(ctx context.Context) ([]domain.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDeleted")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDeleted'
type MockRoleRepository_FindAllDeleted_Call struct {
	*mock.Call
}

// FindAllDeleted is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAllDeleted(ctx interface{}) *MockRoleRepository_FindAllDeleted_Call {
	return &MockRoleRepository_FindAllDeleted_Call{Call: _e.mock.On("FindAllDeleted", ctx)}
}

func (_c *MockRoleRepository_FindAllDeleted_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAllDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllDeleted_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAllDeleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllDeleted_Call) RunAndReturn(run func(context.Context) ([]domain.Role, error)) *MockRoleRepository_FindAllDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDeletedByScope provides a mock function with given fields: ctx, scope
func (_m *MockRoleRepository) FindAllDeletedByScope(ctx context.Context, scope string) ([]domain.Role, error) {
	ret := _m.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDeletedByScope")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllDeletedByScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDeletedByScope'
type MockRoleRepository_FindAllDeletedByScope_Call struct {
	*mock.Call
}

// FindAllDeletedByScope is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
func (_e *MockRoleRepository_Expecter) FindAllDeletedByScope(ctx interface{}, scope interface{}) *MockRoleRepository_FindAllDeletedByScope_Call {
	return &MockRoleRepository_FindAllDeletedByScope_Call{Call: _e.mock.On("FindAllDeletedByScope", ctx, scope)}
}

func (_c *MockRoleRepository_FindAllDeletedByScope_Call) Run(run func(ctx context.Context, scope string)) *MockRoleRepository_FindAllDeletedByScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllDeletedByScope_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAllDeletedByScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllDeletedByScope_Call) RunAndReturn(run func(context.Context, string) ([]domain.Role, error)) *MockRoleRepository_FindAllDeletedByScope_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginated provides a mock function with given fields: ctx, page, size
func (_m *MockRoleRepository) FindAllPaginated(ctx context.Context, page int, size int) ([]domain.Role, error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Role, error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.Role); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginated'
type MockRoleRepository_FindAllPaginated_Call struct {
	*mock.Call
}

// FindAllPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockRoleRepository_Expecter) FindAllPaginated(ctx interface{}, page interface{}, size interface{}) *MockRoleRepository_FindAllPaginated_Call {
	return &MockRoleRepository_FindAllPaginated_Call{Call: _e.mock.On("FindAllPaginated", ctx, page, size)}
}

func (_c *MockRoleRepository_FindAllPaginated_Call) Run(run func(ctx context.Context, page int, size int)) *MockRoleRepository_FindAllPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPaginated_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAllPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPaginated_Call) RunAndReturn(run func(context.Context, int, int) ([]domain.Role, error)) *MockRoleRepository_FindAllPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginatedByScope provides a mock function with given fields: ctx, scope, page, size
func (_m *MockRoleRepository) FindAllPaginatedByScope(ctx context.Context, scope string, page int, size int) ([]domain.Role, error) {
	ret := _m.Called(ctx, scope, page, size)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginatedByScope")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Role, error)); ok {
		return rf(ctx, scope, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Role); ok {
		r0 = rf(ctx, scope, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, scope, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPaginatedByScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginatedByScope'
type MockRoleRepository_FindAllPaginatedByScope_Call struct {
	*mock.Call
}

// FindAllPaginatedByScope is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - page int
//   - size int
func (_e *MockRoleRepository_Expecter) FindAllPaginatedByScope(ctx interface{}, scope interface{}, page interface{}, size interface{}) *MockRoleRepository_FindAllPaginatedByScope_Call {
	return &MockRoleRepository_FindAllPaginatedByScope_Call{Call: _e.mock.On("FindAllPaginatedByScope", ctx, scope, page, size)}
}

func (_c *MockRoleRepository_FindAllPaginatedByScope_Call) Run(run func(ctx context.Context, scope string, page int, size int)) *MockRoleRepository_FindAllPaginatedByScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPaginatedByScope_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindAllPaginatedByScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPaginatedByScope_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Role, error)) *MockRoleRepository_FindAllPaginatedByScope_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissions provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAllPermissions(ctx context.Context) ([]domain.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissions")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissions'
type MockRoleRepository_FindAllPermissions_Call struct {
	*mock.Call
}

// FindAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAllPermissions(ctx interface{}) *MockRoleRepository_FindAllPermissions_Call {
	return &MockRoleRepository_FindAllPermissions_Call{Call: _e.mock.On("FindAllPermissions", ctx)}
}

func (_c *MockRoleRepository_FindAllPermissions_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPermissions_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPermissions_Call) RunAndReturn(run func(context.Context) ([]domain.Permission, error)) *MockRoleRepository_FindAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissionsPaginated provides a mock function with given fields: ctx, page, size
func (_m *MockRoleRepository) FindAllPermissionsPaginated(ctx context.Context, page int, size int) ([]domain.Permission, error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissionsPaginated")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Permission, error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []domain.Permission); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPermissionsPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissionsPaginated'
type MockRoleRepository_FindAllPermissionsPaginated_Call struct {
	*mock.Call
}

// FindAllPermissionsPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockRoleRepository_Expecter) FindAllPermissionsPaginated(ctx interface{}, page interface{}, size interface{}) *MockRoleRepository_FindAllPermissionsPaginated_Call {
	return &MockRoleRepository_FindAllPermissionsPaginated_Call{Call: _e.mock.On("FindAllPermissionsPaginated", ctx, page, size)}
}

func (_c *MockRoleRepository_FindAllPermissionsPaginated_Call) Run(run func(ctx context.Context, page int, size int)) *MockRoleRepository_FindAllPermissionsPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPermissionsPaginated_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleRepository_FindAllPermissionsPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPermissionsPaginated_Call) RunAndReturn(run func(context.Context, int, int) ([]domain.Permission, error)) *MockRoleRepository_FindAllPermissionsPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissionsPaginatedWithTotal provides a mock function with given fields: ctx, page, size
func (_m *MockRoleRepository) FindAllPermissionsPaginatedWithTotal(ctx context.Context, page int, size int) (domain.PaginatedResult[domain.Permission], error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissionsPaginatedWithTotal")
	}

	var r0 domain.PaginatedResult[domain.Permission]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (domain.PaginatedResult[domain.Permission], error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) domain.PaginatedResult[domain.Permission]); ok {
		r0 = rf(ctx, page, size)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.Permission])
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissionsPaginatedWithTotal'
type MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call struct {
	*mock.Call
}

// FindAllPermissionsPaginatedWithTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockRoleRepository_Expecter) FindAllPermissionsPaginatedWithTotal(ctx interface{}, page interface{}, size interface{}) *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call {
	return &MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call{Call: _e.mock.On("FindAllPermissionsPaginatedWithTotal", ctx, page, size)}
}

func (_c *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call) Run(run func(ctx context.Context, page int, size int)) *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call) Return(_a0 domain.PaginatedResult[domain.Permission], _a1 error) *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call) RunAndReturn(run func(context.Context, int, int) (domain.PaginatedResult[domain.Permission], error)) *MockRoleRepository_FindAllPermissionsPaginatedWithTotal_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) FindByID(ctx context.Context, id uint) (*domain.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepository_FindByID_Call {
	return &MockRoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockRoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Role, error)) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepository) FindByName(ctx context.Context, name string) (*domain.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoleRepository_FindByName_Call {
	return &MockRoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) Return(_a0 *domain.Role, _a1 error) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Role, error)) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepository) FindPermissionByName(ctx context.Context, name string) (*domain.Permission, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionByName")
	}

	var r0 *domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Permission, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Permission); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindPermissionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionByName'
type MockRoleRepository_FindPermissionByName_Call struct {
	*mock.Call
}

// FindPermissionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) FindPermissionByName(ctx interface{}, name interface{}) *MockRoleRepository_FindPermissionByName_Call {
	return &MockRoleRepository_FindPermissionByName_Call{Call: _e.mock.On("FindPermissionByName", ctx, name)}
}

func (_c *MockRoleRepository_FindPermissionByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_FindPermissionByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindPermissionByName_Call) Return(_a0 *domain.Permission, _a1 error) *MockRoleRepository_FindPermissionByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindPermissionByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Permission, error)) *MockRoleRepository_FindPermissionByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleRepository) FindPermissionsByIDs(ctx context.Context, ids []uint) ([]domain.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByIDs")
	}

	var r0 []domain.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]domain.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []domain.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindPermissionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByIDs'
type MockRoleRepository_FindPermissionsByIDs_Call struct {
	*mock.Call
}

// FindPermissionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockRoleRepository_Expecter) FindPermissionsByIDs(ctx interface{}, ids interface{}) *MockRoleRepository_FindPermissionsByIDs_Call {
	return &MockRoleRepository_FindPermissionsByIDs_Call{Call: _e.mock.On("FindPermissionsByIDs", ctx, ids)}
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) Return(_a0 []domain.Permission, _a1 error) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindPermissionsByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]domain.Permission, error)) *MockRoleRepository_FindPermissionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindRolesByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRoleRepository) FindRolesByIDs(ctx context.Context, ids []uint) ([]domain.Role, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindRolesByIDs")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]domain.Role, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []domain.Role); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindRolesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRolesByIDs'
type MockRoleRepository_FindRolesByIDs_Call struct {
	*mock.Call
}

// FindRolesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockRoleRepository_Expecter) FindRolesByIDs(ctx interface{}, ids interface{}) *MockRoleRepository_FindRolesByIDs_Call {
	return &MockRoleRepository_FindRolesByIDs_Call{Call: _e.mock.On("FindRolesByIDs", ctx, ids)}
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) Run(run func(ctx context.Context, ids []uint)) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindRolesByIDs_Call) RunAndReturn(run func(context.Context, []uint) ([]domain.Role, error)) *MockRoleRepository_FindRolesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockRoleRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoleRepository_Expecter) Restore(ctx interface{}, id interface{}) *MockRoleRepository_Restore_Call {
	return &MockRoleRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockRoleRepository_Restore_Call) Run(run func(ctx context.Context, id uint)) *MockRoleRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoleRepository_Restore_Call) Return(_a0 error) *MockRoleRepository_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Restore_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoleRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function with given fields: ctx, query
func (_m *MockRoleRepository) SearchByName(ctx context.Context, query string) ([]domain.Role, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Role, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Role); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockRoleRepository_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockRoleRepository_Expecter) SearchByName(ctx interface{}, query interface{}) *MockRoleRepository_SearchByName_Call {
	return &MockRoleRepository_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, query)}
}

func (_c *MockRoleRepository_SearchByName_Call) Run(run func(ctx context.Context, query string)) *MockRoleRepository_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_SearchByName_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_SearchByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_SearchByName_Call) RunAndReturn(run func(context.Context, string) ([]domain.Role, error)) *MockRoleRepository_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByNameAndScope provides a mock function with given fields: ctx, query, scope
func (_m *MockRoleRepository) SearchByNameAndScope(ctx context.Context, query string, scope string) ([]domain.Role, error) {
	ret := _m.Called(ctx, query, scope)

	if len(ret) == 0 {
		panic("no return value specified for SearchByNameAndScope")
	}

	var r0 []domain.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.Role, error)); ok {
		return rf(ctx, query, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.Role); ok {
		r0 = rf(ctx, query, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, query, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_SearchByNameAndScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByNameAndScope'
type MockRoleRepository_SearchByNameAndScope_Call struct {
	*mock.Call
}

// SearchByNameAndScope is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - scope string
func (_e *MockRoleRepository_Expecter) SearchByNameAndScope(ctx interface{}, query interface{}, scope interface{}) *MockRoleRepository_SearchByNameAndScope_Call {
	return &MockRoleRepository_SearchByNameAndScope_Call{Call: _e.mock.On("SearchByNameAndScope", ctx, query, scope)}
}

func (_c *MockRoleRepository_SearchByNameAndScope_Call) Run(run func(ctx context.Context, query string, scope string)) *MockRoleRepository_SearchByNameAndScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_SearchByNameAndScope_Call) Return(_a0 []domain.Role, _a1 error) *MockRoleRepository_SearchByNameAndScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_SearchByNameAndScope_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.Role, error)) *MockRoleRepository_SearchByNameAndScope_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Update(ctx context.Context, role *domain.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *domain.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, role *domain.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(_a0 error) *MockRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Role) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function with given fields: ctx, perm
func (_m *MockRoleRepository) UpdatePermission(ctx context.Context, perm *domain.Permission) error {
	ret := _m.Called(ctx, perm)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Permission) error); ok {
		r0 = rf(ctx, perm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockRoleRepository_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - perm *domain.Permission
func (_e *MockRoleRepository_Expecter) UpdatePermission(ctx interface{}, perm interface{}) *MockRoleRepository_UpdatePermission_Call {
	return &MockRoleRepository_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, perm)}
}

func (_c *MockRoleRepository_UpdatePermission_Call) Run(run func(ctx context.Context, perm *domain.Permission)) *MockRoleRepository_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Permission))
	})
	return _c
}

func (_c *MockRoleRepository_UpdatePermission_Call) Return(_a0 error) *MockRoleRepository_UpdatePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_UpdatePermission_Call) RunAndReturn(run func(context.Context, *domain.Permission) error) *MockRoleRepository_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
