// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	domain "github.com/MargonDiego/GOAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, storedName
func (_m *MockFileStorage) Delete(ctx context.Context, storedName string) error {
	ret := _m.Called(ctx, storedName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, storedName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - storedName string
func (_e *MockFileStorage_Expecter) Delete(ctx interface{}, storedName interface{}) *MockFileStorage_Delete_Call {
	return &MockFileStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, storedName)}
}

func (_c *MockFileStorage_Delete_Call) Run(run func(ctx context.Context, storedName string)) *MockFileStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileStorage_Delete_Call) Return(_a0 error) *MockFileStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockFileStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, storedName
func (_m *MockFileStorage) Open(ctx context.Context, storedName string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, storedName)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, storedName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, storedName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storedName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorage_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFileStorage_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - storedName string
func (_e *MockFileStorage_Expecter) Open(ctx interface{}, storedName interface{}) *MockFileStorage_Open_Call {
	return &MockFileStorage_Open_Call{Call: _e.mock.On("Open", ctx, storedName)}
}

func (_c *MockFileStorage_Open_Call) Run(run func(ctx context.Context, storedName string)) *MockFileStorage_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileStorage_Open_Call) Return(_a0 io.ReadCloser, _a1 error) *MockFileStorage_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorage_Open_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockFileStorage_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, r, meta
func (_m *MockFileStorage) Save(ctx context.Context, r io.Reader, meta domain.FileMeta) (domain.StoredFile, error) {
	ret := _m.Called(ctx, r, meta)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 domain.StoredFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, domain.FileMeta) (domain.StoredFile, error)); ok {
		return rf(ctx, r, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, domain.FileMeta) domain.StoredFile); ok {
		r0 = rf(ctx, r, meta)
	} else {
		r0 = ret.Get(0).(domain.StoredFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, domain.FileMeta) error); ok {
		r1 = rf(ctx, r, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockFileStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
//   - meta domain.FileMeta
func (_e *MockFileStorage_Expecter) Save(ctx interface{}, r interface{}, meta interface{}) *MockFileStorage_Save_Call {
	return &MockFileStorage_Save_Call{Call: _e.mock.On("Save", ctx, r, meta)}
}

func (_c *MockFileStorage_Save_Call) Run(run func(ctx context.Context, r io.Reader, meta domain.FileMeta)) *MockFileStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(domain.FileMeta))
	})
	return _c
}

func (_c *MockFileStorage_Save_Call) Return(_a0 domain.StoredFile, _a1 error) *MockFileStorage_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorage_Save_Call) RunAndReturn(run func(context.Context, io.Reader, domain.FileMeta) (domain.StoredFile, error)) *MockFileStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
