// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/MargonDiego/GOAPI/internal/application"

	domain "github.com/MargonDiego/GOAPI/internal/domain"

	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIncidenciaService is an autogenerated mock type for the IncidenciaService type
type MockIncidenciaService struct {
	mock.Mock
}

type MockIncidenciaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncidenciaService) EXPECT() *MockIncidenciaService_Expecter {
	return &MockIncidenciaService_Expecter{mock: &_m.Mock}
}

// AdjuntarArchivo provides a mock function with given fields: ctx, id, r, meta
func (_m *MockIncidenciaService) AdjuntarArchivo(ctx context.Context, id uint, r io.Reader, meta domain.FileMeta) (*domain.Adjunto, error) {
	ret := _m.Called(ctx, id, r, meta)

	if len(ret) == 0 {
		panic("no return value specified for AdjuntarArchivo")
	}

	var r0 *domain.Adjunto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, io.Reader, domain.FileMeta) (*domain.Adjunto, error)); ok {
		return rf(ctx, id, r, meta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, io.Reader, domain.FileMeta) *domain.Adjunto); ok {
		r0 = rf(ctx, id, r, meta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Adjunto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, io.Reader, domain.FileMeta) error); ok {
		r1 = rf(ctx, id, r, meta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncidenciaService_AdjuntarArchivo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjuntarArchivo'
type MockIncidenciaService_AdjuntarArchivo_Call struct {
	*mock.Call
}

// AdjuntarArchivo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - r io.Reader
//   - meta domain.FileMeta
func (_e *MockIncidenciaService_Expecter) AdjuntarArchivo(ctx interface{}, id interface{}, r interface{}, meta interface{}) *MockIncidenciaService_AdjuntarArchivo_Call {
	return &MockIncidenciaService_AdjuntarArchivo_Call{Call: _e.mock.On("AdjuntarArchivo", ctx, id, r, meta)}
}

func (_c *MockIncidenciaService_AdjuntarArchivo_Call) Run(run func(ctx context.Context, id uint, r io.Reader, meta domain.FileMeta)) *MockIncidenciaService_AdjuntarArchivo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(io.Reader), args[3].(domain.FileMeta))
	})
	return _c
}

func (_c *MockIncidenciaService_AdjuntarArchivo_Call) Return(_a0 *domain.Adjunto, _a1 error) *MockIncidenciaService_AdjuntarArchivo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncidenciaService_AdjuntarArchivo_Call) RunAndReturn(run func(context.Context, uint, io.Reader, domain.FileMeta) (*domain.Adjunto, error)) *MockIncidenciaService_AdjuntarArchivo_Call {
	_c.Call.Return(run)
	return _c
}

// AgregarComentario provides a mock function with given fields: ctx, id, cuerpo
func (_m *MockIncidenciaService) AgregarComentario(ctx context.Context, id uint, cuerpo string) error {
	ret := _m.Called(ctx, id, cuerpo)

	if len(ret) == 0 {
		panic("no return value specified for AgregarComentario")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, id, cuerpo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_AgregarComentario_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgregarComentario'
type MockIncidenciaService_AgregarComentario_Call struct {
	*mock.Call
}

// AgregarComentario is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - cuerpo string
func (_e *MockIncidenciaService_Expecter) AgregarComentario(ctx interface{}, id interface{}, cuerpo interface{}) *MockIncidenciaService_AgregarComentario_Call {
	return &MockIncidenciaService_AgregarComentario_Call{Call: _e.mock.On("AgregarComentario", ctx, id, cuerpo)}
}

func (_c *MockIncidenciaService_AgregarComentario_Call) Run(run func(ctx context.Context, id uint, cuerpo string)) *MockIncidenciaService_AgregarComentario_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockIncidenciaService_AgregarComentario_Call) Return(_a0 error) *MockIncidenciaService_AgregarComentario_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_AgregarComentario_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockIncidenciaService_AgregarComentario_Call {
	_c.Call.Return(run)
	return _c
}

// Asignar provides a mock function with given fields: ctx, id, responsableID
func (_m *MockIncidenciaService) Asignar(ctx context.Context, id uint, responsableID uint) error {
	ret := _m.Called(ctx, id, responsableID)

	if len(ret) == 0 {
		panic("no return value specified for Asignar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, responsableID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_Asignar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Asignar'
type MockIncidenciaService_Asignar_Call struct {
	*mock.Call
}

// Asignar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - responsableID uint
func (_e *MockIncidenciaService_Expecter) Asignar(ctx interface{}, id interface{}, responsableID interface{}) *MockIncidenciaService_Asignar_Call {
	return &MockIncidenciaService_Asignar_Call{Call: _e.mock.On("Asignar", ctx, id, responsableID)}
}

func (_c *MockIncidenciaService_Asignar_Call) Run(run func(ctx context.Context, id uint, responsableID uint)) *MockIncidenciaService_Asignar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_Asignar_Call) Return(_a0 error) *MockIncidenciaService_Asignar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_Asignar_Call) RunAndReturn(run func(context.Context, uint, uint) error) *MockIncidenciaService_Asignar_Call {
	_c.Call.Return(run)
	return _c
}

// Cerrar provides a mock function with given fields: ctx, id
func (_m *MockIncidenciaService) Cerrar(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cerrar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_Cerrar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cerrar'
type MockIncidenciaService_Cerrar_Call struct {
	*mock.Call
}

// Cerrar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIncidenciaService_Expecter) Cerrar(ctx interface{}, id interface{}) *MockIncidenciaService_Cerrar_Call {
	return &MockIncidenciaService_Cerrar_Call{Call: _e.mock.On("Cerrar", ctx, id)}
}

func (_c *MockIncidenciaService_Cerrar_Call) Run(run func(ctx context.Context, id uint)) *MockIncidenciaService_Cerrar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_Cerrar_Call) Return(_a0 error) *MockIncidenciaService_Cerrar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_Cerrar_Call) RunAndReturn(run func(context.Context, uint) error) *MockIncidenciaService_Cerrar_Call {
	_c.Call.Return(run)
	return _c
}

// Crear provides a mock function with given fields: ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito
func (_m *MockIncidenciaService) Crear(ctx context.Context, estudianteID uint, titulo string, descripcion string, gravedad domain.GravedadIncidencia, categoria domain.CategoriaIncidencia, esDelito bool) (*domain.Incidencia, error) {
	ret := _m.Called(ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito)

	if len(ret) == 0 {
		panic("no return value specified for Crear")
	}

	var r0 *domain.Incidencia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, domain.GravedadIncidencia, domain.CategoriaIncidencia, bool) (*domain.Incidencia, error)); ok {
		return rf(ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, domain.GravedadIncidencia, domain.CategoriaIncidencia, bool) *domain.Incidencia); ok {
		r0 = rf(ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Incidencia)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, string, domain.GravedadIncidencia, domain.CategoriaIncidencia, bool) error); ok {
		r1 = rf(ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncidenciaService_Crear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Crear'
type MockIncidenciaService_Crear_Call struct {
	*mock.Call
}

// Crear is a helper method to define mock.On call
//   - ctx context.Context
//   - estudianteID uint
//   - titulo string
//   - descripcion string
//   - gravedad domain.GravedadIncidencia
//   - categoria domain.CategoriaIncidencia
//   - esDelito bool
func (_e *MockIncidenciaService_Expecter) Crear(ctx interface{}, estudianteID interface{}, titulo interface{}, descripcion interface{}, gravedad interface{}, categoria interface{}, esDelito interface{}) *MockIncidenciaService_Crear_Call {
	return &MockIncidenciaService_Crear_Call{Call: _e.mock.On("Crear", ctx, estudianteID, titulo, descripcion, gravedad, categoria, esDelito)}
}

func (_c *MockIncidenciaService_Crear_Call) Run(run func(ctx context.Context, estudianteID uint, titulo string, descripcion string, gravedad domain.GravedadIncidencia, categoria domain.CategoriaIncidencia, esDelito bool)) *MockIncidenciaService_Crear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(domain.GravedadIncidencia), args[5].(domain.CategoriaIncidencia), args[6].(bool))
	})
	return _c
}

func (_c *MockIncidenciaService_Crear_Call) Return(_a0 *domain.Incidencia, _a1 error) *MockIncidenciaService_Crear_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncidenciaService_Crear_Call) RunAndReturn(run func(context.Context, uint, string, string, domain.GravedadIncidencia, domain.CategoriaIncidencia, bool) (*domain.Incidencia, error)) *MockIncidenciaService_Crear_Call {
	_c.Call.Return(run)
	return _c
}

// Derivar provides a mock function with given fields: ctx, id
func (_m *MockIncidenciaService) Derivar(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Derivar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_Derivar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Derivar'
type MockIncidenciaService_Derivar_Call struct {
	*mock.Call
}

// Derivar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIncidenciaService_Expecter) Derivar(ctx interface{}, id interface{}) *MockIncidenciaService_Derivar_Call {
	return &MockIncidenciaService_Derivar_Call{Call: _e.mock.On("Derivar", ctx, id)}
}

func (_c *MockIncidenciaService_Derivar_Call) Run(run func(ctx context.Context, id uint)) *MockIncidenciaService_Derivar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_Derivar_Call) Return(_a0 error) *MockIncidenciaService_Derivar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_Derivar_Call) RunAndReturn(run func(context.Context, uint) error) *MockIncidenciaService_Derivar_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIncidenciaService) GetByID(ctx context.Context, id uint) (*domain.Incidencia, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Incidencia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Incidencia, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Incidencia); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Incidencia)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncidenciaService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIncidenciaService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIncidenciaService_Expecter) GetByID(ctx interface{}, id interface{}) *MockIncidenciaService_GetByID_Call {
	return &MockIncidenciaService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIncidenciaService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockIncidenciaService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_GetByID_Call) Return(_a0 *domain.Incidencia, _a1 error) *MockIncidenciaService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncidenciaService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Incidencia, error)) *MockIncidenciaService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpediente provides a mock function with given fields: ctx, id
func (_m *MockIncidenciaService) GetExpediente(ctx context.Context, id uint) (*application.Expediente, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExpediente")
	}

	var r0 *application.Expediente
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*application.Expediente, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *application.Expediente); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*application.Expediente)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncidenciaService_GetExpediente_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpediente'
type MockIncidenciaService_GetExpediente_Call struct {
	*mock.Call
}

// GetExpediente is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIncidenciaService_Expecter) GetExpediente(ctx interface{}, id interface{}) *MockIncidenciaService_GetExpediente_Call {
	return &MockIncidenciaService_GetExpediente_Call{Call: _e.mock.On("GetExpediente", ctx, id)}
}

func (_c *MockIncidenciaService_GetExpediente_Call) Run(run func(ctx context.Context, id uint)) *MockIncidenciaService_GetExpediente_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_GetExpediente_Call) Return(_a0 *application.Expediente, _a1 error) *MockIncidenciaService_GetExpediente_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncidenciaService_GetExpediente_Call) RunAndReturn(run func(context.Context, uint) (*application.Expediente, error)) *MockIncidenciaService_GetExpediente_Call {
	_c.Call.Return(run)
	return _c
}

// IniciarInvestigacion provides a mock function with given fields: ctx, id, fecha
func (_m *MockIncidenciaService) IniciarInvestigacion(ctx context.Context, id uint, fecha time.Time) error {
	ret := _m.Called(ctx, id, fecha)

	if len(ret) == 0 {
		panic("no return value specified for IniciarInvestigacion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) error); ok {
		r0 = rf(ctx, id, fecha)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_IniciarInvestigacion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IniciarInvestigacion'
type MockIncidenciaService_IniciarInvestigacion_Call struct {
	*mock.Call
}

// IniciarInvestigacion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - fecha time.Time
func (_e *MockIncidenciaService_Expecter) IniciarInvestigacion(ctx interface{}, id interface{}, fecha interface{}) *MockIncidenciaService_IniciarInvestigacion_Call {
	return &MockIncidenciaService_IniciarInvestigacion_Call{Call: _e.mock.On("IniciarInvestigacion", ctx, id, fecha)}
}

func (_c *MockIncidenciaService_IniciarInvestigacion_Call) Run(run func(ctx context.Context, id uint, fecha time.Time)) *MockIncidenciaService_IniciarInvestigacion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIncidenciaService_IniciarInvestigacion_Call) Return(_a0 error) *MockIncidenciaService_IniciarInvestigacion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_IniciarInvestigacion_Call) RunAndReturn(run func(context.Context, uint, time.Time) error) *MockIncidenciaService_IniciarInvestigacion_Call {
	_c.Call.Return(run)
	return _c
}

// IniciarSeguimiento provides a mock function with given fields: ctx, id
func (_m *MockIncidenciaService) IniciarSeguimiento(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IniciarSeguimiento")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_IniciarSeguimiento_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IniciarSeguimiento'
type MockIncidenciaService_IniciarSeguimiento_Call struct {
	*mock.Call
}

// IniciarSeguimiento is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIncidenciaService_Expecter) IniciarSeguimiento(ctx interface{}, id interface{}) *MockIncidenciaService_IniciarSeguimiento_Call {
	return &MockIncidenciaService_IniciarSeguimiento_Call{Call: _e.mock.On("IniciarSeguimiento", ctx, id)}
}

func (_c *MockIncidenciaService_IniciarSeguimiento_Call) Run(run func(ctx context.Context, id uint)) *MockIncidenciaService_IniciarSeguimiento_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_IniciarSeguimiento_Call) Return(_a0 error) *MockIncidenciaService_IniciarSeguimiento_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_IniciarSeguimiento_Call) RunAndReturn(run func(context.Context, uint) error) *MockIncidenciaService_IniciarSeguimiento_Call {
	_c.Call.Return(run)
	return _c
}

// ObtenerAdjunto provides a mock function with given fields: ctx, adjID
func (_m *MockIncidenciaService) ObtenerAdjunto(ctx context.Context, adjID uint) (*domain.Adjunto, io.ReadCloser, error) {
	ret := _m.Called(ctx, adjID)

	if len(ret) == 0 {
		panic("no return value specified for ObtenerAdjunto")
	}

	var r0 *domain.Adjunto
	var r1 io.ReadCloser
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Adjunto, io.ReadCloser, error)); ok {
		return rf(ctx, adjID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Adjunto); ok {
		r0 = rf(ctx, adjID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Adjunto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) io.ReadCloser); ok {
		r1 = rf(ctx, adjID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint) error); ok {
		r2 = rf(ctx, adjID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIncidenciaService_ObtenerAdjunto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObtenerAdjunto'
type MockIncidenciaService_ObtenerAdjunto_Call struct {
	*mock.Call
}

// ObtenerAdjunto is a helper method to define mock.On call
//   - ctx context.Context
//   - adjID uint
func (_e *MockIncidenciaService_Expecter) ObtenerAdjunto(ctx interface{}, adjID interface{}) *MockIncidenciaService_ObtenerAdjunto_Call {
	return &MockIncidenciaService_ObtenerAdjunto_Call{Call: _e.mock.On("ObtenerAdjunto", ctx, adjID)}
}

func (_c *MockIncidenciaService_ObtenerAdjunto_Call) Run(run func(ctx context.Context, adjID uint)) *MockIncidenciaService_ObtenerAdjunto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIncidenciaService_ObtenerAdjunto_Call) Return(_a0 *domain.Adjunto, _a1 io.ReadCloser, _a2 error) *MockIncidenciaService_ObtenerAdjunto_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIncidenciaService_ObtenerAdjunto_Call) RunAndReturn(run func(context.Context, uint) (*domain.Adjunto, io.ReadCloser, error)) *MockIncidenciaService_ObtenerAdjunto_Call {
	_c.Call.Return(run)
	return _c
}

// PresentarApelacion provides a mock function with given fields: ctx, id, resolucionID, motivo, plazoVencimiento
func (_m *MockIncidenciaService) PresentarApelacion(ctx context.Context, id uint, resolucionID uint, motivo string, plazoVencimiento time.Time) error {
	ret := _m.Called(ctx, id, resolucionID, motivo, plazoVencimiento)

	if len(ret) == 0 {
		panic("no return value specified for PresentarApelacion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, time.Time) error); ok {
		r0 = rf(ctx, id, resolucionID, motivo, plazoVencimiento)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_PresentarApelacion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresentarApelacion'
type MockIncidenciaService_PresentarApelacion_Call struct {
	*mock.Call
}

// PresentarApelacion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - resolucionID uint
//   - motivo string
//   - plazoVencimiento time.Time
func (_e *MockIncidenciaService_Expecter) PresentarApelacion(ctx interface{}, id interface{}, resolucionID interface{}, motivo interface{}, plazoVencimiento interface{}) *MockIncidenciaService_PresentarApelacion_Call {
	return &MockIncidenciaService_PresentarApelacion_Call{Call: _e.mock.On("PresentarApelacion", ctx, id, resolucionID, motivo, plazoVencimiento)}
}

func (_c *MockIncidenciaService_PresentarApelacion_Call) Run(run func(ctx context.Context, id uint, resolucionID uint, motivo string, plazoVencimiento time.Time)) *MockIncidenciaService_PresentarApelacion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockIncidenciaService_PresentarApelacion_Call) Return(_a0 error) *MockIncidenciaService_PresentarApelacion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_PresentarApelacion_Call) RunAndReturn(run func(context.Context, uint, uint, string, time.Time) error) *MockIncidenciaService_PresentarApelacion_Call {
	_c.Call.Return(run)
	return _c
}

// RegistrarDescargo provides a mock function with given fields: ctx, id, contenido
func (_m *MockIncidenciaService) RegistrarDescargo(ctx context.Context, id uint, contenido string) error {
	ret := _m.Called(ctx, id, contenido)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarDescargo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, id, contenido)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_RegistrarDescargo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegistrarDescargo'
type MockIncidenciaService_RegistrarDescargo_Call struct {
	*mock.Call
}

// RegistrarDescargo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - contenido string
func (_e *MockIncidenciaService_Expecter) RegistrarDescargo(ctx interface{}, id interface{}, contenido interface{}) *MockIncidenciaService_RegistrarDescargo_Call {
	return &MockIncidenciaService_RegistrarDescargo_Call{Call: _e.mock.On("RegistrarDescargo", ctx, id, contenido)}
}

func (_c *MockIncidenciaService_RegistrarDescargo_Call) Run(run func(ctx context.Context, id uint, contenido string)) *MockIncidenciaService_RegistrarDescargo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *MockIncidenciaService_RegistrarDescargo_Call) Return(_a0 error) *MockIncidenciaService_RegistrarDescargo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_RegistrarDescargo_Call) RunAndReturn(run func(context.Context, uint, string) error) *MockIncidenciaService_RegistrarDescargo_Call {
	_c.Call.Return(run)
	return _c
}

// RegistrarMedida provides a mock function with given fields: ctx, id, clase, tipo, descripcion, proporcionalidad, responsableEjecID, fechaInicio, fechaTermino
func (_m *MockIncidenciaService) RegistrarMedida(ctx context.Context, id uint, clase domain.ClaseMedida, tipo domain.TipoMedida, descripcion string, proporcionalidad string, responsableEjecID uint, fechaInicio time.Time, fechaTermino *time.Time) error {
	ret := _m.Called(ctx, id, clase, tipo, descripcion, proporcionalidad, responsableEjecID, fechaInicio, fechaTermino)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarMedida")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, domain.ClaseMedida, domain.TipoMedida, string, string, uint, time.Time, *time.Time) error); ok {
		r0 = rf(ctx, id, clase, tipo, descripcion, proporcionalidad, responsableEjecID, fechaInicio, fechaTermino)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_RegistrarMedida_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegistrarMedida'
type MockIncidenciaService_RegistrarMedida_Call struct {
	*mock.Call
}

// RegistrarMedida is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - clase domain.ClaseMedida
//   - tipo domain.TipoMedida
//   - descripcion string
//   - proporcionalidad string
//   - responsableEjecID uint
//   - fechaInicio time.Time
//   - fechaTermino *time.Time
func (_e *MockIncidenciaService_Expecter) RegistrarMedida(ctx interface{}, id interface{}, clase interface{}, tipo interface{}, descripcion interface{}, proporcionalidad interface{}, responsableEjecID interface{}, fechaInicio interface{}, fechaTermino interface{}) *MockIncidenciaService_RegistrarMedida_Call {
	return &MockIncidenciaService_RegistrarMedida_Call{Call: _e.mock.On("RegistrarMedida", ctx, id, clase, tipo, descripcion, proporcionalidad, responsableEjecID, fechaInicio, fechaTermino)}
}

func (_c *MockIncidenciaService_RegistrarMedida_Call) Run(run func(ctx context.Context, id uint, clase domain.ClaseMedida, tipo domain.TipoMedida, descripcion string, proporcionalidad string, responsableEjecID uint, fechaInicio time.Time, fechaTermino *time.Time)) *MockIncidenciaService_RegistrarMedida_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(domain.ClaseMedida), args[3].(domain.TipoMedida), args[4].(string), args[5].(string), args[6].(uint), args[7].(time.Time), args[8].(*time.Time))
	})
	return _c
}

func (_c *MockIncidenciaService_RegistrarMedida_Call) Return(_a0 error) *MockIncidenciaService_RegistrarMedida_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_RegistrarMedida_Call) RunAndReturn(run func(context.Context, uint, domain.ClaseMedida, domain.TipoMedida, string, string, uint, time.Time, *time.Time) error) *MockIncidenciaService_RegistrarMedida_Call {
	_c.Call.Return(run)
	return _c
}

// RegistrarNotificacion provides a mock function with given fields: ctx, id, destinatario, medio, contenido, fecha
func (_m *MockIncidenciaService) RegistrarNotificacion(ctx context.Context, id uint, destinatario string, medio string, contenido string, fecha time.Time) error {
	ret := _m.Called(ctx, id, destinatario, medio, contenido, fecha)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarNotificacion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, id, destinatario, medio, contenido, fecha)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_RegistrarNotificacion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegistrarNotificacion'
type MockIncidenciaService_RegistrarNotificacion_Call struct {
	*mock.Call
}

// RegistrarNotificacion is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - destinatario string
//   - medio string
//   - contenido string
//   - fecha time.Time
func (_e *MockIncidenciaService_Expecter) RegistrarNotificacion(ctx interface{}, id interface{}, destinatario interface{}, medio interface{}, contenido interface{}, fecha interface{}) *MockIncidenciaService_RegistrarNotificacion_Call {
	return &MockIncidenciaService_RegistrarNotificacion_Call{Call: _e.mock.On("RegistrarNotificacion", ctx, id, destinatario, medio, contenido, fecha)}
}

func (_c *MockIncidenciaService_RegistrarNotificacion_Call) Run(run func(ctx context.Context, id uint, destinatario string, medio string, contenido string, fecha time.Time)) *MockIncidenciaService_RegistrarNotificacion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(string), args[5].(time.Time))
	})
	return _c
}

func (_c *MockIncidenciaService_RegistrarNotificacion_Call) Return(_a0 error) *MockIncidenciaService_RegistrarNotificacion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_RegistrarNotificacion_Call) RunAndReturn(run func(context.Context, uint, string, string, string, time.Time) error) *MockIncidenciaService_RegistrarNotificacion_Call {
	_c.Call.Return(run)
	return _c
}

// Resolver provides a mock function with given fields: ctx, id, fundamentacion, decision
func (_m *MockIncidenciaService) Resolver(ctx context.Context, id uint, fundamentacion string, decision string) error {
	ret := _m.Called(ctx, id, fundamentacion, decision)

	if len(ret) == 0 {
		panic("no return value specified for Resolver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, id, fundamentacion, decision)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_Resolver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolver'
type MockIncidenciaService_Resolver_Call struct {
	*mock.Call
}

// Resolver is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - fundamentacion string
//   - decision string
func (_e *MockIncidenciaService_Expecter) Resolver(ctx interface{}, id interface{}, fundamentacion interface{}, decision interface{}) *MockIncidenciaService_Resolver_Call {
	return &MockIncidenciaService_Resolver_Call{Call: _e.mock.On("Resolver", ctx, id, fundamentacion, decision)}
}

func (_c *MockIncidenciaService_Resolver_Call) Run(run func(ctx context.Context, id uint, fundamentacion string, decision string)) *MockIncidenciaService_Resolver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockIncidenciaService_Resolver_Call) Return(_a0 error) *MockIncidenciaService_Resolver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_Resolver_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockIncidenciaService_Resolver_Call {
	_c.Call.Return(run)
	return _c
}

// ResolverApelacion provides a mock function with given fields: ctx, apelacionID, fundamentacion, decision, aceptada
func (_m *MockIncidenciaService) ResolverApelacion(ctx context.Context, apelacionID uint, fundamentacion string, decision string, aceptada bool) error {
	ret := _m.Called(ctx, apelacionID, fundamentacion, decision, aceptada)

	if len(ret) == 0 {
		panic("no return value specified for ResolverApelacion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, bool) error); ok {
		r0 = rf(ctx, apelacionID, fundamentacion, decision, aceptada)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIncidenciaService_ResolverApelacion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolverApelacion'
type MockIncidenciaService_ResolverApelacion_Call struct {
	*mock.Call
}

// ResolverApelacion is a helper method to define mock.On call
//   - ctx context.Context
//   - apelacionID uint
//   - fundamentacion string
//   - decision string
//   - aceptada bool
func (_e *MockIncidenciaService_Expecter) ResolverApelacion(ctx interface{}, apelacionID interface{}, fundamentacion interface{}, decision interface{}, aceptada interface{}) *MockIncidenciaService_ResolverApelacion_Call {
	return &MockIncidenciaService_ResolverApelacion_Call{Call: _e.mock.On("ResolverApelacion", ctx, apelacionID, fundamentacion, decision, aceptada)}
}

func (_c *MockIncidenciaService_ResolverApelacion_Call) Run(run func(ctx context.Context, apelacionID uint, fundamentacion string, decision string, aceptada bool)) *MockIncidenciaService_ResolverApelacion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockIncidenciaService_ResolverApelacion_Call) Return(_a0 error) *MockIncidenciaService_ResolverApelacion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIncidenciaService_ResolverApelacion_Call) RunAndReturn(run func(context.Context, uint, string, string, bool) error) *MockIncidenciaService_ResolverApelacion_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, f, page, size
func (_m *MockIncidenciaService) Search(ctx context.Context, f domain.IncidenciaFilter, page int, size int) (domain.PaginatedResult[domain.Incidencia], error) {
	ret := _m.Called(ctx, f, page, size)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.PaginatedResult[domain.Incidencia]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.IncidenciaFilter, int, int) (domain.PaginatedResult[domain.Incidencia], error)); ok {
		return rf(ctx, f, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.IncidenciaFilter, int, int) domain.PaginatedResult[domain.Incidencia]); ok {
		r0 = rf(ctx, f, page, size)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.Incidencia])
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.IncidenciaFilter, int, int) error); ok {
		r1 = rf(ctx, f, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIncidenciaService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockIncidenciaService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - f domain.IncidenciaFilter
//   - page int
//   - size int
func (_e *MockIncidenciaService_Expecter) Search(ctx interface{}, f interface{}, page interface{}, size interface{}) *MockIncidenciaService_Search_Call {
	return &MockIncidenciaService_Search_Call{Call: _e.mock.On("Search", ctx, f, page, size)}
}

func (_c *MockIncidenciaService_Search_Call) Run(run func(ctx context.Context, f domain.IncidenciaFilter, page int, size int)) *MockIncidenciaService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.IncidenciaFilter), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIncidenciaService_Search_Call) Return(_a0 domain.PaginatedResult[domain.Incidencia], _a1 error) *MockIncidenciaService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIncidenciaService_Search_Call) RunAndReturn(run func(context.Context, domain.IncidenciaFilter, int, int) (domain.PaginatedResult[domain.Incidencia], error)) *MockIncidenciaService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIncidenciaService creates a new instance of MockIncidenciaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncidenciaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncidenciaService {
	mock := &MockIncidenciaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
