// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/MargonDiego/GOAPI/internal/application"

	domain "github.com/MargonDiego/GOAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockEstudianteService is an autogenerated mock type for the EstudianteService type
type MockEstudianteService struct {
	mock.Mock
}

type MockEstudianteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEstudianteService) EXPECT() *MockEstudianteService_Expecter {
	return &MockEstudianteService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rut, nombre, curso
func (_m *MockEstudianteService) Create(ctx context.Context, rut string, nombre string, curso string) error {
	ret := _m.Called(ctx, rut, nombre, curso)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, rut, nombre, curso)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEstudianteService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rut string
//   - nombre string
//   - curso string
func (_e *MockEstudianteService_Expecter) Create(ctx interface{}, rut interface{}, nombre interface{}, curso interface{}) *MockEstudianteService_Create_Call {
	return &MockEstudianteService_Create_Call{Call: _e.mock.On("Create", ctx, rut, nombre, curso)}
}

func (_c *MockEstudianteService_Create_Call) Run(run func(ctx context.Context, rut string, nombre string, curso string)) *MockEstudianteService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEstudianteService_Create_Call) Return(_a0 error) *MockEstudianteService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteService_Create_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockEstudianteService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEstudianteService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEstudianteService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteService_Expecter) Delete(ctx interface{}, id interface{}) *MockEstudianteService_Delete_Call {
	return &MockEstudianteService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEstudianteService_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteService_Delete_Call) Return(_a0 error) *MockEstudianteService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteService_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockEstudianteService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockEstudianteService) GetByID(ctx context.Context, id uint) (application.EstudianteData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 application.EstudianteData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (application.EstudianteData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) application.EstudianteData); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(application.EstudianteData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockEstudianteService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteService_Expecter) GetByID(ctx interface{}, id interface{}) *MockEstudianteService_GetByID_Call {
	return &MockEstudianteService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockEstudianteService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteService_GetByID_Call) Return(_a0 application.EstudianteData, _a1 error) *MockEstudianteService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (application.EstudianteData, error)) *MockEstudianteService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockEstudianteService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteService_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockEstudianteService_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteService_Expecter) Restore(ctx interface{}, id interface{}) *MockEstudianteService_Restore_Call {
	return &MockEstudianteService_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockEstudianteService_Restore_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteService_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteService_Restore_Call) Return(_a0 error) *MockEstudianteService_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteService_Restore_Call) RunAndReturn(run func(context.Context, uint) error) *MockEstudianteService_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, curso, page, size
func (_m *MockEstudianteService) Search(ctx context.Context, curso string, page int, size int) (domain.PaginatedResult[application.EstudianteData], error) {
	ret := _m.Called(ctx, curso, page, size)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 domain.PaginatedResult[application.EstudianteData]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (domain.PaginatedResult[application.EstudianteData], error)); ok {
		return rf(ctx, curso, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) domain.PaginatedResult[application.EstudianteData]); ok {
		r0 = rf(ctx, curso, page, size)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[application.EstudianteData])
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, curso, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockEstudianteService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - curso string
//   - page int
//   - size int
func (_e *MockEstudianteService_Expecter) Search(ctx interface{}, curso interface{}, page interface{}, size interface{}) *MockEstudianteService_Search_Call {
	return &MockEstudianteService_Search_Call{Call: _e.mock.On("Search", ctx, curso, page, size)}
}

func (_c *MockEstudianteService_Search_Call) Run(run func(ctx context.Context, curso string, page int, size int)) *MockEstudianteService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockEstudianteService_Search_Call) Return(_a0 domain.PaginatedResult[application.EstudianteData], _a1 error) *MockEstudianteService_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteService_Search_Call) RunAndReturn(run func(context.Context, string, int, int) (domain.PaginatedResult[application.EstudianteData], error)) *MockEstudianteService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatos provides a mock function with given fields: ctx, id, nombre, curso
func (_m *MockEstudianteService) UpdateDatos(ctx context.Context, id uint, nombre string, curso string) error {
	ret := _m.Called(ctx, id, nombre, curso)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatos")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, id, nombre, curso)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteService_UpdateDatos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatos'
type MockEstudianteService_UpdateDatos_Call struct {
	*mock.Call
}

// UpdateDatos is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - nombre string
//   - curso string
func (_e *MockEstudianteService_Expecter) UpdateDatos(ctx interface{}, id interface{}, nombre interface{}, curso interface{}) *MockEstudianteService_UpdateDatos_Call {
	return &MockEstudianteService_UpdateDatos_Call{Call: _e.mock.On("UpdateDatos", ctx, id, nombre, curso)}
}

func (_c *MockEstudianteService_UpdateDatos_Call) Run(run func(ctx context.Context, id uint, nombre string, curso string)) *MockEstudianteService_UpdateDatos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEstudianteService_UpdateDatos_Call) Return(_a0 error) *MockEstudianteService_UpdateDatos_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteService_UpdateDatos_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockEstudianteService_UpdateDatos_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEstudianteService creates a new instance of MockEstudianteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEstudianteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEstudianteService {
	mock := &MockEstudianteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
