// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/MargonDiego/GOAPI/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditRepository is an autogenerated mock type for the AuditRepository type
type MockAuditRepository struct {
	mock.Mock
}

type MockAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditRepository) EXPECT() *MockAuditRepository_Expecter {
	return &MockAuditRepository_Expecter{mock: &_m.Mock}
}

// Log provides a mock function with given fields: ctx, log
func (_m *MockAuditRepository) Log(ctx context.Context, log *domain.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditRepository_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockAuditRepository_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - log *domain.AuditLog
func (_e *MockAuditRepository_Expecter) Log(ctx interface{}, log interface{}) *MockAuditRepository_Log_Call {
	return &MockAuditRepository_Log_Call{Call: _e.mock.On("Log", ctx, log)}
}

func (_c *MockAuditRepository_Log_Call) Run(run func(ctx context.Context, log *domain.AuditLog)) *MockAuditRepository_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuditLog))
	})
	return _c
}

func (_c *MockAuditRepository_Log_Call) Return(_a0 error) *MockAuditRepository_Log_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditRepository_Log_Call) RunAndReturn(run func(context.Context, *domain.AuditLog) error) *MockAuditRepository_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditRepository creates a new instance of MockAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditRepository {
	mock := &MockAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
