// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/MargonDiego/GOAPI/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockEstudianteRepository is an autogenerated mock type for the EstudianteRepository type
type MockEstudianteRepository struct {
	mock.Mock
}

type MockEstudianteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEstudianteRepository) EXPECT() *MockEstudianteRepository_Expecter {
	return &MockEstudianteRepository_Expecter{mock: &_m.Mock}
}

// CountSearch provides a mock function with given fields: ctx, curso, scope
func (_m *MockEstudianteRepository) CountSearch(ctx context.Context, curso string, scope string) (int64, error) {
	ret := _m.Called(ctx, curso, scope)

	if len(ret) == 0 {
		panic("no return value specified for CountSearch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, curso, scope)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, curso, scope)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, curso, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteRepository_CountSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSearch'
type MockEstudianteRepository_CountSearch_Call struct {
	*mock.Call
}

// CountSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - curso string
//   - scope string
func (_e *MockEstudianteRepository_Expecter) CountSearch(ctx interface{}, curso interface{}, scope interface{}) *MockEstudianteRepository_CountSearch_Call {
	return &MockEstudianteRepository_CountSearch_Call{Call: _e.mock.On("CountSearch", ctx, curso, scope)}
}

func (_c *MockEstudianteRepository_CountSearch_Call) Run(run func(ctx context.Context, curso string, scope string)) *MockEstudianteRepository_CountSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockEstudianteRepository_CountSearch_Call) Return(_a0 int64, _a1 error) *MockEstudianteRepository_CountSearch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteRepository_CountSearch_Call) RunAndReturn(run func(context.Context, string, string) (int64, error)) *MockEstudianteRepository_CountSearch_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, e
func (_m *MockEstudianteRepository) Create(ctx context.Context, e *domain.Estudiante) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Estudiante) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEstudianteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *domain.Estudiante
func (_e *MockEstudianteRepository_Expecter) Create(ctx interface{}, e interface{}) *MockEstudianteRepository_Create_Call {
	return &MockEstudianteRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockEstudianteRepository_Create_Call) Run(run func(ctx context.Context, e *domain.Estudiante)) *MockEstudianteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Estudiante))
	})
	return _c
}

func (_c *MockEstudianteRepository_Create_Call) Return(_a0 error) *MockEstudianteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Estudiante) error) *MockEstudianteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockEstudianteRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEstudianteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEstudianteRepository_Delete_Call {
	return &MockEstudianteRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEstudianteRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteRepository_Delete_Call) Return(_a0 error) *MockEstudianteRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockEstudianteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockEstudianteRepository) FindByID(ctx context.Context, id uint) (*domain.Estudiante, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Estudiante
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Estudiante, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Estudiante); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Estudiante)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockEstudianteRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockEstudianteRepository_FindByID_Call {
	return &MockEstudianteRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockEstudianteRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteRepository_FindByID_Call) Return(_a0 *domain.Estudiante, _a1 error) *MockEstudianteRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Estudiante, error)) *MockEstudianteRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRutHash provides a mock function with given fields: ctx, rutHash
func (_m *MockEstudianteRepository) FindByRutHash(ctx context.Context, rutHash string) (*domain.Estudiante, error) {
	ret := _m.Called(ctx, rutHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByRutHash")
	}

	var r0 *domain.Estudiante
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Estudiante, error)); ok {
		return rf(ctx, rutHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Estudiante); ok {
		r0 = rf(ctx, rutHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Estudiante)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rutHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteRepository_FindByRutHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRutHash'
type MockEstudianteRepository_FindByRutHash_Call struct {
	*mock.Call
}

// FindByRutHash is a helper method to define mock.On call
//   - ctx context.Context
//   - rutHash string
func (_e *MockEstudianteRepository_Expecter) FindByRutHash(ctx interface{}, rutHash interface{}) *MockEstudianteRepository_FindByRutHash_Call {
	return &MockEstudianteRepository_FindByRutHash_Call{Call: _e.mock.On("FindByRutHash", ctx, rutHash)}
}

func (_c *MockEstudianteRepository_FindByRutHash_Call) Run(run func(ctx context.Context, rutHash string)) *MockEstudianteRepository_FindByRutHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEstudianteRepository_FindByRutHash_Call) Return(_a0 *domain.Estudiante, _a1 error) *MockEstudianteRepository_FindByRutHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteRepository_FindByRutHash_Call) RunAndReturn(run func(context.Context, string) (*domain.Estudiante, error)) *MockEstudianteRepository_FindByRutHash_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockEstudianteRepository) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockEstudianteRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockEstudianteRepository_Expecter) Restore(ctx interface{}, id interface{}) *MockEstudianteRepository_Restore_Call {
	return &MockEstudianteRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockEstudianteRepository_Restore_Call) Run(run func(ctx context.Context, id uint)) *MockEstudianteRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockEstudianteRepository_Restore_Call) Return(_a0 error) *MockEstudianteRepository_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteRepository_Restore_Call) RunAndReturn(run func(context.Context, uint) error) *MockEstudianteRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, curso, scope, page, size
func (_m *MockEstudianteRepository) Search(ctx context.Context, curso string, scope string, page int, size int) ([]domain.Estudiante, error) {
	ret := _m.Called(ctx, curso, scope, page, size)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.Estudiante
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]domain.Estudiante, error)); ok {
		return rf(ctx, curso, scope, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []domain.Estudiante); ok {
		r0 = rf(ctx, curso, scope, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Estudiante)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, curso, scope, page, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEstudianteRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockEstudianteRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - curso string
//   - scope string
//   - page int
//   - size int
func (_e *MockEstudianteRepository_Expecter) Search(ctx interface{}, curso interface{}, scope interface{}, page interface{}, size interface{}) *MockEstudianteRepository_Search_Call {
	return &MockEstudianteRepository_Search_Call{Call: _e.mock.On("Search", ctx, curso, scope, page, size)}
}

func (_c *MockEstudianteRepository_Search_Call) Run(run func(ctx context.Context, curso string, scope string, page int, size int)) *MockEstudianteRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockEstudianteRepository_Search_Call) Return(_a0 []domain.Estudiante, _a1 error) *MockEstudianteRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEstudianteRepository_Search_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]domain.Estudiante, error)) *MockEstudianteRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDatos provides a mock function with given fields: ctx, e
func (_m *MockEstudianteRepository) UpdateDatos(ctx context.Context, e *domain.Estudiante) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDatos")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Estudiante) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEstudianteRepository_UpdateDatos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDatos'
type MockEstudianteRepository_UpdateDatos_Call struct {
	*mock.Call
}

// UpdateDatos is a helper method to define mock.On call
//   - ctx context.Context
//   - e *domain.Estudiante
func (_e *MockEstudianteRepository_Expecter) UpdateDatos(ctx interface{}, e interface{}) *MockEstudianteRepository_UpdateDatos_Call {
	return &MockEstudianteRepository_UpdateDatos_Call{Call: _e.mock.On("UpdateDatos", ctx, e)}
}

func (_c *MockEstudianteRepository_UpdateDatos_Call) Run(run func(ctx context.Context, e *domain.Estudiante)) *MockEstudianteRepository_UpdateDatos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Estudiante))
	})
	return _c
}

func (_c *MockEstudianteRepository_UpdateDatos_Call) Return(_a0 error) *MockEstudianteRepository_UpdateDatos_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEstudianteRepository_UpdateDatos_Call) RunAndReturn(run func(context.Context, *domain.Estudiante) error) *MockEstudianteRepository_UpdateDatos_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEstudianteRepository creates a new instance of MockEstudianteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEstudianteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEstudianteRepository {
	mock := &MockEstudianteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
